{{- if .Values.tcpService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress
data:
  {{ .Values.tcpService.externalPort }}: "{{ .Release.Namespace }}/{{ .Release.Name }}:{{ .Values.tcpService.port }}"
{{- end }}
---
{{- if .Values.tcpService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: ingress
data:
  {{ .Values.udpService.externalPort }}: "{{ .Release.Namespace }}/{{ .Release.Name }}:{{ .Values.udpService.port }}"
{{- end }}