apiVersion: v1
kind: Service
metadata:
  name: {{ include "phrike.fullname" . }}
  labels:
    {{- include "phrike.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: proxied-tcp-external
      port: {{ .Values.tcpService.externalPort }}
      targetPort: {{ .Values.tcpService.externalPort }}
      protocol: TCP
    - name: proxied-udp-external
      port: {{ .Values.udpService.externalPort }}
      targetPort: {{ .Values.udpService.externalPort }}
      protocol: UDP
  selector:
    {{- include "phrike.selectorLabels" . | nindent 4 }}
