apiVersion: v1
kind: Service
metadata:
  name: {{ include "phrike.fullname" . }}
  labels:
    {{- include "phrike.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 7777
      protocol: TCP
  selector:
    {{- include "phrike.selectorLabels" . | nindent 4 }}
