{{- if .Values.udpService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: {{ .Values.udpService.type }}
  ports:
    - name: proxied-udp-external
      port: {{ Values.tcpService.externalPort }}
      targetPort: {{ Values.tcpService.externalPort }}
      protocol: UDP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
{{- end }}